ansible_user: ubuntu
ansible_connection: local
kubeadm_control_plane: true
etcd_cert_dir: /etc/ssl/etcd/ssl
kube_etcd_cacert_file: ca.crt
kube_etcd_cert_file: etcdctl-etcd-client.crt
kube_etcd_key_file: etcdctl-etcd-client.key

ignore_assert_errors: true
container_manager: containerd
